// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Game struct {
	Date              string `json:"date"`
	HomeTeam          *Team  `json:"homeTeam"`
	AwayTeam          *Team  `json:"awayTeam"`
	Winner            *Team  `json:"winner"`
	HomeFinalScore    int32  `json:"homeFinalScore"`
	AwayFinalScore    int32  `json:"awayFinalScore"`
	HomeFirstQuarter  int32  `json:"homeFirstQuarter"`
	AwayFirstQuarter  int32  `json:"awayFirstQuarter"`
	HomeSecondQuarter int32  `json:"homeSecondQuarter"`
	AwaySecondQuarter int32  `json:"awaySecondQuarter"`
	HomeThirdQuarter  int32  `json:"homeThirdQuarter"`
	AwayThirdQuarter  int32  `json:"awayThirdQuarter"`
	HomeFourthQuarter int32  `json:"homeFourthQuarter"`
	AwayFourthQuarter int32  `json:"awayFourthQuarter"`
	HomeOvertime      *int32 `json:"homeOvertime,omitempty"`
	AwayOvertime      *int32 `json:"awayOvertime,omitempty"`
}

type Mutation struct {
}

type NewGame struct {
	Date              string `json:"date"`
	HomeTeam          string `json:"homeTeam"`
	AwayTeam          string `json:"awayTeam"`
	HomeFinalScore    int32  `json:"homeFinalScore"`
	AwayFinalScore    int32  `json:"awayFinalScore"`
	HomeFirstQuarter  int32  `json:"homeFirstQuarter"`
	AwayFirstQuarter  int32  `json:"awayFirstQuarter"`
	HomeSecondQuarter int32  `json:"homeSecondQuarter"`
	AwaySecondQuarter int32  `json:"awaySecondQuarter"`
	HomeThirdQuarter  int32  `json:"homeThirdQuarter"`
	AwayThirdQuarter  int32  `json:"awayThirdQuarter"`
	HomeFourthQuarter int32  `json:"homeFourthQuarter"`
	AwayFourthQuarter int32  `json:"awayFourthQuarter"`
	HomeOvertime      *int32 `json:"homeOvertime,omitempty"`
	AwayOvertime      *int32 `json:"awayOvertime,omitempty"`
}

type Query struct {
}

type Team struct {
	City       string `json:"city"`
	Name       string `json:"name"`
	TotalWins  int32  `json:"totalWins"`
	TotalLoses int32  `json:"totalLoses"`
}
